apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default # İleride bunu cloudmason namespace'ine alabiliriz
  labels:
    app: api-gateway
spec:
  replicas: 2 # Yüksek erişilebilirlik (HA) için 2 kopya çalıştırıyoruz
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: egbayram/api-gateway:v1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          # SRE Pratiği: Container'ın yaşayıp yaşamadığını kontrol eden problar
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
