apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  labels:
    # Prometheus operatörü, sadece bu etikete (release) sahip olanları dikkate alır!
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-gateway # Hangi servisi dinleyeceğini buradan anlıyor
  endpoints:
  - port: http # Service'te verdiğimiz port ismi
    path: /metrics # Fiber middleware'inin metrikleri sunduğu yol
    interval: 15s # 15 saniyede bir gidip verileri çekecek
